export const candidateProfileContract = {
  uiGenerationDefaults: {
    disableDetailSectionWhenAllChildFieldsEmpty: true,
    emptyRawValues: ['', 'NA', 'N/A', 'null', 'None', '[]', '{}'],
    emptyScalars: ['', null],
    hideEmptySummaryFields: true,
    placeholderValues: ['Nil', 'Not Given', '---------No Cases--------'],
  },
  fieldCatalog: {
    state_name: { formatter: 'plain_text', type: 'string' },
    state_slug: { formatter: 'slug', type: 'string' },
    election_year: { formatter: 'year', type: 'number' },
    election_type: { formatter: 'plain_text', type: 'string' },
    scope: { formatter: 'plain_text', type: 'string' },
    is_winner: { formatter: 'boolean_badge', type: 'boolean' },
    result_label: { formatter: 'badge', type: 'string' },
    candidate_id: { formatter: 'plain_text', type: 'string' },
    display_name: { formatter: 'plain_text', type: 'string' },
    profile_url: { formatter: 'external_link', type: 'url' },
    constituency_label: { formatter: 'plain_text', type: 'string' },
    constituency_name: { formatter: 'plain_text', type: 'string' },
    seat_reservation: { formatter: 'badge', type: 'string' },
    party: { formatter: 'plain_text', type: 'string' },
    age: { formatter: 'years', type: 'number' },
    education_category: { formatter: 'badge', type: 'string' },
    education_details: { formatter: 'paragraph', type: 'string' },
    criminal_case_count: { formatter: 'integer', type: 'number' },
    has_criminal_cases: { formatter: 'boolean_badge', type: 'boolean' },
    assets_amount_inr: { formatter: 'inr_compact', type: 'currency_inr' },
    assets_label: { formatter: 'plain_text', type: 'string' },
    liabilities_amount_inr: { formatter: 'inr_compact', type: 'currency_inr' },
    liabilities_label: { formatter: 'plain_text', type: 'string' },
    net_assets_amount_inr: { formatter: 'inr_compact', type: 'currency_inr' },
    self_profession: { formatter: 'plain_text', type: 'string' },
    spouse_profession: { formatter: 'plain_text', type: 'string' },
    relative_name: { formatter: 'plain_text', type: 'string' },
    voter_roll_info: { formatter: 'paragraph', type: 'string' },
    accused_cases: { formatter: 'table', type: 'json_array' },
    convicted_cases: { formatter: 'table', type: 'json_array' },
    liability_breakdown: { formatter: 'table', type: 'json_array' },
    movable_assets_breakdown: { formatter: 'table', type: 'json_array' },
    immovable_assets_breakdown: { formatter: 'table', type: 'json_array' },
  },
  uiLayout: {
    summaryBrief: [
      {
        comparisonReady: true,
        fieldId: 'display_name',
        label: 'Candidate',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'result_label',
        label: 'Result',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'state_name',
        label: 'State',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'election_year',
        label: 'Year',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'election_type',
        label: 'Election Type',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'party',
        label: 'Party',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'constituency_label',
        label: 'Constituency',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'seat_reservation',
        label: 'Seat Reservation',
        required: false,
      },
      {
        comparisonReady: true,
        fieldId: 'age',
        label: 'Age',
        required: false,
      },
      {
        comparisonReady: true,
        fieldId: 'education_category',
        label: 'Education',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'criminal_case_count',
        label: 'Criminal Cases',
        required: true,
      },
      {
        comparisonReady: true,
        fieldId: 'assets_amount_inr',
        label: 'Assets',
        required: false,
      },
      {
        comparisonReady: true,
        fieldId: 'liabilities_amount_inr',
        label: 'Liabilities',
        required: false,
      },
      {
        comparisonReady: true,
        fieldId: 'net_assets_amount_inr',
        label: 'Net Assets',
        required: false,
      },
      {
        comparisonReady: true,
        fieldId: 'self_profession',
        label: 'Profession',
        required: false,
      },
    ],
    detailsSections: [
      {
        description: 'Core election metadata and source identifiers for the candidate.',
        disableWhenAllFieldsEmpty: true,
        fields: [
          'state_name',
          'election_year',
          'election_type',
          'result_label',
          'constituency_label',
          'seat_reservation',
          'candidate_id',
          'profile_url',
        ],
        label: 'Election Context',
        sectionId: 'election_context',
      },
      {
        description: 'Basic profile and family-related fields.',
        disableWhenAllFieldsEmpty: true,
        fields: ['age', 'relative_name', 'self_profession', 'spouse_profession'],
        label: 'Personal and Family',
        sectionId: 'personal_and_family',
      },
      {
        description:
          'Education category for quick reading plus the longer affidavit text when present.',
        disableWhenAllFieldsEmpty: true,
        fields: ['education_category', 'education_details'],
        label: 'Education',
        sectionId: 'education',
      },
      {
        description:
          'Top-line financial numbers suitable for normal reading without expanding raw tables.',
        disableWhenAllFieldsEmpty: true,
        fields: [
          'assets_amount_inr',
          'assets_label',
          'liabilities_amount_inr',
          'liabilities_label',
          'net_assets_amount_inr',
        ],
        label: 'Financial Overview',
        sectionId: 'finance_overview',
      },
      {
        description:
          'Expandable affidavit table data for liabilities and any parsed movable or immovable asset tables.',
        disableWhenAllFieldsEmpty: true,
        enableWhenAny: [
          'liability_breakdown',
          'movable_assets_breakdown',
          'immovable_assets_breakdown',
        ],
        fields: ['liability_breakdown', 'movable_assets_breakdown', 'immovable_assets_breakdown'],
        label: 'Affidavit Breakdown',
        sectionId: 'finance_breakdown',
      },
      {
        description:
          'Detailed accused and convicted case tables. Keep disabled when no meaningful case data exists.',
        disableWhenAllFieldsEmpty: true,
        enableWhenAny: ['criminal_case_count > 0', 'accused_cases', 'convicted_cases'],
        fields: ['criminal_case_count', 'accused_cases', 'convicted_cases'],
        label: 'Legal Details',
        sectionId: 'legal_details',
      },
      {
        description: 'Source URL and voter roll text useful for auditability and trace-back.',
        disableWhenAllFieldsEmpty: true,
        fields: ['voter_roll_info', 'profile_url'],
        label: 'Voter Roll and Source',
        sectionId: 'voter_and_source',
      },
    ],
  },
} as const;

export type ProfileFieldId = keyof typeof candidateProfileContract.fieldCatalog;
export type DetailSectionId =
  (typeof candidateProfileContract.uiLayout.detailsSections)[number]['sectionId'];
export type ProfileFieldFormatter =
  (typeof candidateProfileContract.fieldCatalog)[ProfileFieldId]['formatter'];
